baseURL: "https://kamotake.com/"
languageCode: "ja"
title: "かもたけ"
theme: "hugo-PaperMod"

canonifyURLs: true

params:
  defaultTheme: dark
  disableThemeToggle: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml


menu:
  main:
    - identifier: posts
      name: 記事
      url: /posts/
      weight: 10
    - identifier: profile
      name: プロフィール
      url: /profile/
      weight: 20

