baseURL: "https://kamotake.com/"
canonifyURLs: true
languageCode: "ja"
title: "かもたけ"
theme: "hugo-PaperMod"

canonifyURLs: true

params:
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  env: production

  meta:
    - name: google-site-verification
      content: "D8mTU1e6pvMEHn-1s-IITN5999ooK8ACoxIG-Cf-OlU"

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml


menu:
  main:
    - identifier: posts
      name: 記事
      url: /posts/
      weight: 10
    - identifier: profile
      name: プロフィール
      url: /profile/
      weight: 20

